#!/bin/sh

cd /tmpbt

cp device.hints /boot/zm.dev
cp loader.conf /boot/zm.ld
cp logo_freebsd.c /sys/dev/vt/logo/logo_freebsd.c
cp AOS /usr/src/sys/amd64/conf/AOS
unzip new.rc.d.zip 
cd rc.d 
chmod -R +x .
cd ..
mv rc.d /etc/zm.rc.d
cd /tmpbt 
